name: Testbench CI
on:
  push:
  # Runs on all PRs
  pull_request:
  # Manual Dispatch
  workflow_dispatch:

jobs:
  testbench:
    strategy:
      fail-fast: false
      matrix:
        testbench: [lumi/testbench/test_lumi.py, lumi/testbench/test_lumi_rnd.py, umi/testbench/test_crossbar.py, umi/testbench/test_fifo_flex.py, umi/testbench/test_fifo.py, umi/testbench/test_mem_agent.py, umi/testbench/test_regif.py, utils/testbench/test_umi_address_remap.py, utils/testbench/test_umi_packet_merge_greedy.py, utils/testbench/test_umi2tl_np.py]
    
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/zeroasiccorp/sbtest:latest

    steps:
      - name: Check out UMI
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Install requirements
        run: |
          python3 -m venv .venv
          . .venv/bin/activate
          python3 -m pip install --upgrade pip
          python3 -m pip install switchboard-hw

      - name: Run ${{ matrix.testbench }}
        run: |
          . .venv/bin/activate
          cd $(dirname "${{ matrix.testbench }}")
          ./$(basename "${{ matrix.testbench }}")
